---
version: '3.5'
services:
  nitter:
    volumes:
      - ./nitter.conf:/src/nitter.conf
    image: zedeus/nitter:latest
    restart: unless-stopped
    container_name: nitter
    ports:
      - "8080:8080"
    healthcheck:
      test: [
        "CMD",
        "wget",
        "--no-verbose",
        "--tries=1",
        "--spider",
        "http://localhost:8080"
      ]
      interval: 1m
      timeout: 3s
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
