# https://github.com/iv-org/invidious/blob/master/docker-compose.yml
# https://github.com/zedeus/nitter/blob/master/docker-compose.yml
# https://yacy.net/download_installation/#docker
version: '3.7'
services:
  nitter:
    volumes:
    - ./nitter.conf:/src/nitter.conf
    image: zedeus/nitter:latest
    restart: unless-stopped
    container_name: nitter
    ports:
    - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 1m
      timeout: 3s
    depends_on:
    - nitter-redis
  nitter-redis:
    image: redis:6-alpine
    container_name: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    volumes:
    - nitter-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/London
    - AUTO_UPDATE=true    # optional
      # - RUN_OPTS=<run options here>  # optional
    volumes:
    - ./jackett/config:/config
    - ./jackett/downloads:/downloads
    ports:
    - 9117:9117
    restart: unless-stopped
  invidious:
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    ports:
    - 127.0.0.1:3000:3000
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    depends_on:
    - invidious-db
  invidious-db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
    - postgresdata:/var/lib/postgresql/data
    - ./config/sql:/config/sql
    - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: [CMD-SHELL, pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB]
  tachidesk:
    image: ghcr.io/suwayomi/tachidesk
    restart: unless-stopped
    ports:
    - "4567:4567"
  yacy:
    container_name: yacy
    image: yacy/yacy_search_server:latest
    restart: unless-stopped
    ports:
    - "8090:8090"
    - "8443:8443"
    volumes:
    - "yacy_data:/opt/yacy_search_server/DATA"
    logging:
      options:
        max-size: "200m"
        max-file: "2"

volumes:
  nitter-redis:
  postgresdata:
